"""Seed realistic Pakistani demo data and write local login credentials.

Run: ``python3 seed.py``
The generated credentials file is ignored by Git and is for local development only.
"""

from pathlib import Path

from app.db.database import init_database
from app.db.session import SessionLocal
from app.services.demo_data_service import DemoAccount, DemoDataService, DemoSeedResult


CREDENTIALS_FILE = Path(__file__).resolve().with_name("credentials.txt")


def write_credentials(result: DemoSeedResult) -> None:
    lines = [
        "LOCAL REALISTIC-DEMO CREDENTIALS",
        "Generated by seed.py. Never use these accounts or passwords in production.",
        "",
    ]
    admins = [account for account in result.credentials if account.email == result.summary.admin_email]
    if admins:
        lines.extend(["ADMIN", f"Name: {admins[0].full_name}", f"Email: {admins[0].email}", f"Password: {admins[0].password}", ""])
    else:
        lines.extend(["ADMIN", f"Email: {result.summary.admin_email}", "Password: existing account password was preserved", ""])

    lines.append("EDITORS")
    for index, account in enumerate((item for item in result.credentials if item.email != result.summary.admin_email), start=1):
        lines.extend(
            [
                f"{index}. {account.full_name}",
                f"   Email: {account.email}",
                f"   Password: {account.password}",
            ]
        )
    CREDENTIALS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    init_database()
    with SessionLocal() as db:
        result = DemoDataService(db).seed(replace_legacy_mock_data=True)
    write_credentials(result)
    summary = result.summary
    print(
        "Seeded realistic Pakistani demo data: "
        f"{summary.cities} cities, {summary.editors} editors, {summary.listings} listings "
        f"({summary.approved_listings} approved / {summary.pending_listings} pending)."
    )
    print(f"Credentials written to {CREDENTIALS_FILE.name}")


if __name__ == "__main__":
    main()
